version: "3.3"
services:
  web:
    image: docker-node-ticker
    build: .
    command: "npm start"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ticket-mongo
    ports:
      - "27017:27017"
